site_name: Sunday Usman
site_description: This is my website.
site_author: Sunday Usman
site_url: 'https://sundayusman.github.io/FOSS2024-tutorial-sunday/'

# Repository
repo_name: FOSS24 Tutorial Sunday
repo_url: 'https://github.com/sundayusman/FOSS2024-tutorial-sunday'
edit_uri: edit/main/docs/

# Copyright
copyright: 'Copyright &copy; 2023 - 2024'

# Configuration
theme:
  name: material
  highlightjs: true
  font:
    text: Roboto
    code: Regular
  palette:
    scheme: default
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs  # Enables horizontal tabs at the top
    - navigation.tabs.sticky  # Makes the tabs stay at the top when scrolling
    - navigation.indexes
    - navigation.top
  icon:
    logo: material/cogs
    favicon: material/cogs

# Features  
features:
- navigation.instant
- navigation.tracking
- toc.follow

# 404 page
static_templates:
    - 404.html

# Search feature
include_search_page: false
search_index_only: true

# Palette and theme (uses personalized colours)
palette:
    primary: teal
    accent: orange
    scheme: slate
    toggle:
        icon: material/weather-night
        name: Switch mode
    toggles:
        - icon: material/weather-sunny
          name: Light mode
        - icon: material/weather-night
          name: Dark mode

# Page tree (Navigation bar at the top)
nav:
- Home: index.md
- Publications: publications.md
- Presentations: presentations.md
- Interviews: interviews.md
- Skills & Experience: skills.md
- Portfolio: portfolio.md
- Testimonials: testimonials.md
- Contact: contact.md

# Extra Plugins
plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
        include_source: True
        ignore_h1_titles: True

# Extensions (leave as is)
markdown_extensions:
- admonition
- abbr
- attr_list
- def_list
- footnotes
- meta
- md_in_html
- toc:
    permalink: true
    title: On this page
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink:
    repo_url_shorthand: true
    user: squidfunk
    repo: mkdocs-material
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde

# Custom CSS for text justification
extra_css:
  - assets/css/style.css
